<p>Cliquer sur le bouton sauvegarder ressources régulièrement et AVANT CHAQUE ACTION</p>
<p>NE JAMAIS ACTUALISER/RAFRAICHIR LA PAGE (TOUCHE F5)</p>
<P>TOUJOURS ATTENDRE LE MESSAGE DE REUSSITE DE L'ACTION AVANT D'EN LANCER UNE AUTRE</P>