<div id="div-town">
    <h2>Ville</h2>
    <p class="tooltip"><img class="img-resource" src="../pictures/wheat.png" alt="Nourriture" />Nourriture : <span id="town-food"><?php echo number_format((float)$_SESSION['player']->getTown_food(), 0, ',', ' '); ?></span><span class="tooltiptext"><?php echo number_format(360 * (1 + (int)$_SESSION['player']->getLevel_farm() * 5), 0, ',', ' ') . ' /h'; ?></span> </p>
    <p class="tooltip"><img class="img-resource" src="../pictures/wood1.png" alt="Bois" />Bois : <span id="town-wood"><?php echo number_format((float)$_SESSION['player']->getTown_wood(), 0, ',', ' '); ?></span><span class="tooltiptext"><?php echo number_format(360 * (1 + (int)$_SESSION['player']->getLevel_sawmill() * 4), 0, ',', ' ') . ' /h'; ?></span> </p>
    <p class="tooltip"><img class="img-resource" src="../pictures/metal1.png" alt="Métal" />Métal : <span id="town-metal"><?php echo number_format((float)$_SESSION['player']->getTown_metal(), 0, ',', ' '); ?></span><span class="tooltiptext"><?php echo number_format(360 * (0 + (int)$_SESSION['player']->getLevel_extractor() * 3), 0, ',', ' ') . ' /h'; ?></span> </p>
    <p class="tooltip"><img class="img-resource" src="../pictures/stone1.png" alt="Pierre" />Pierre : <span id="town-stone"><?php echo number_format((float)$_SESSION['player']->getTown_stone(), 0, ',', ' '); ?></span><span class="tooltiptext"><?php echo number_format(360 * (0 + (int)$_SESSION['player']->getLevel_quarry() * 2), 0, ',', ' ') . ' /h'; ?></span> </p>
    <p class="tooltip"><img class="img-resource" src="../pictures/multigold1.png" alt="Or" />Or : <span id="town-gold"><?php echo number_format((float)$_SESSION['player']->getTown_gold(), 0, ',', ' '); ?></span><span class="tooltiptext"><?php echo number_format(360 * (0 + (int)$_SESSION['player']->getLevel_mine() * 1), 0, ',', ' ') . ' /h'; ?></span> </p>

    <p class="tooltip">Arcs dans la ville : <span id="town-bow"><?php echo number_format((float)$_SESSION['player']->getTown_bow(), 0, ',', ' '); ?></span><span class="tooltiptext"><?php echo number_format(360 * (0 + (int)$_SESSION['player']->getLevel_workshop() * 1), 0, ',', ' ') . ' /h'; ?></span> </p>
    <p class="tooltip">Arbalètes dans la ville : <span id="town-crossbow"><?php echo number_format((float)$_SESSION['player']->getTown_crossbow(), 0, ',', ' '); ?></span><span class="tooltiptext"><?php echo number_format(360 * (0 + (int)$_SESSION['player']->getLevel_workshop() * 1), 0, ',', ' ') . ' /h'; ?></span> </p>
</div>