<?php

?>

<p>Carte</p>

<table>
    <tr>
        <td>Monstre</td>
        <td>Vide</td>
        <td>Nourriture</td>
        <td>Monstre</td>
        <td>Vide</td>
        <td>Nourriture</td>
        <td>Monstre</td>
        <td>Vide</td>
        <td>Nourriture</td>
    </tr>
    <tr>
        <td>Bois</td>
        <td>Vide</td>
        <td>Bois</td>
        <td>Bois</td>
        <td>Vide</td>
        <td>Pierre</td>
        <td>Bois</td>
        <td>Vide</td>
        <td>Pierre</td>
    </tr>
    <tr>
        <td>Monstre</td>
        <td>Vide</td>
        <td>Métal</td>
        <td>Monstre</td>
        <td>Vide</td>
        <td>Métal</td>
        <td>Monstre</td>
        <td>Vide</td>
        <td>Métal</td>
    </tr>
    <tr>
        <td>Monstre</td>
        <td>Vide</td>
        <td>Métal</td>
        <td>Monstre</td>
        <td>Vide</td>
        <td>Métal</td>
        <td>Monstre</td>
        <td>Vide</td>
        <td>Métal</td>
    </tr>
</table>